# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'http://ruby.taobao.org'

gem "middleman", "~>3.3.12"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.4.2"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]

gem "middleman-bower", github: "bbtfr/middleman-bower"
gem "middleman-deploy"

gem "bourbon"
gem 'sprockets-coffee-react'
