# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman"
gem "middleman-livereload"
gem "middleman-bower", github: "bbtfr/middleman-bower"
gem "middleman-deploy"

gem "eco"

gem "bourbon"
# gem "frontend-toolkit", github: "bbtfr/frontend-toolkit"
gem "frontend-toolkit", path: "../../../RUBY"

gem "redcarpet"
